### PR TITLE
Bump optifine compat

### PR DESCRIPTION
**Pull request by Nightenom**
# Changes proposed in this pull request:
- bump optifine compat to work properly in g7/g8 versions

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
Oh cmon, fix the whitespacing of your IDE xD Or git setup

**Comment by Nightenom** [comment]
> Oh cmon, fix the whitespacing of your IDE xD Or git setup

Did change the config now, haven't touched it before tho :D

**Review by marchermans — CHANGES_REQUESTED** [review]
Fix your whitespacing.
This is not acceptable in the current state.

**Comment by Nightenom** [comment]
> Fix your whitespacing.
> This is not acceptable in the current state.

You know you can hide whitespace changes in Github files page? and also I've said we should add .gitattribute with autocrlf to make sure git doesn't explode for everyone, you've said no - really not sure why though

if you really want me to change this commit then put reaction on this (im not now able to do so, will do tomorrow if needed)

**Comment by uecasm** [comment]
`autocrlf` is evil.  Although I do recommend setting `.gitattributes` with `* -text` to force all clients to **not** do CRLF transformations, rather than relying on people on Windows to use the correct settings instead of the defaults.  Though that might be a pain in the butt initially for those people using the incorrect defaults.

**Review by Raycoms — APPROVED** [review]

**Review by marchermans — APPROVED** [review]

**Pull request merged**
