### PR TITLE
Back to the custom names 1.20

### PR DESCRIPTION
**Pull request by uecasm**
Closes [discord request](https://discord.com/channels/472875599422291968/1156041864433107014)

# Changes proposed in this pull request:
- If the anchor block has a `name=Something` tag (directly on itself), this name will be used in place of the blueprint's filename.
    - This is primarily intended to give nicer names to decorations that would otherwise just appear as their (possibly numbered) filename, but it can also be used to override the "alternates" name shown for MineColonies buildings.
    - The tag must be used consistently at all levels of the blueprint, otherwise they will "split".
    - There is currently no way to translate this name, but that's not different from existing behaviour.  A translation PR will follow.
- When you click on a blueprint button that has alternatives and/or levels, previously the list of folders/blueprints at the bottom was completely cleared.  Now, a back button remains, allowing you to return to the list of blueprints that was visible previously, to allow quickly inspecting in and out of related buildings.
- The `isInvisible` check has been extracted to a utility method since MineColonies wants to be able to call it too.

Review please (could port)

This is a port of #614 but it has a different implementation that doesn't override the building name.

### CODE REVIEW

**Review by Raycoms — APPROVED** [review]

**Comment by uecasm** [comment]
Not really sure what the difference is between `1.20.1` and `main` or why the base branch was changed.  But what else is needed to merge this?

**Comment by Thodor12** [comment]
`version/main` is now where the porting to 1.20.4 is happening

**Comment by uecasm** [comment]
> `version/main` is now where the porting to 1.20.4 is happening

Not according to the commit history, it isn't.

**Comment by Nightenom** [comment]
It stems from miscommunication between Ray and me, when I thought we agreed on making main stale during porting to mitigate conflicts in porting branch (and also mark where did the porting split happen to later merge all unported commits) - this was applied successfully on blockui, not so successfully here..

**Pull request merged**
