### PR TITLE
Fix blueprint rotation change upon selecting new blueprint

### LINKED ISSUE #389: Build tool remembers "mirror" state between buildings
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.177-alpha
- MineColonies Version (if related bug): 0.14.210-alpha
- Related Mods and their Versions: n/a

## Expected behavior

When you end a build tool session (green checkmark, red x, or either creative mode paste) the build tool forgets whatever the mirror setting was on the next use, like with rotation and positioning.

## Actual behavior

Mirror is remembered, leading to other structures being mirrored (potentially triggering bugs like https://github.com/ldtteam/minecolonies/issues/5006#issuecomment-856323324 or #377)

## Steps to reproduce the issue

1. Start placing a structure and choose to mirror it
2. Either finish placing the structure, or cancel the placement
3. Start placing another structure where you can tell if it's mirrored

### Logs

Logs do not show this issue

### Notes
I bet this is easy to fix but I haven't looked at the build tool code and I need to go to bed tonight instead of fixing it.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### LINKED ISSUE #8719: Rotating/mirroring works wonky (when facing East or West)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1071-ALPHA

### Structurize Version

structurize-1.19.2-1.0.457-ALPHA

### Related Mods and their Versions

Minecolonies Colony Venture pack, on the patreon server

### Current Behavior

I noticed this first with Shire builder building, but just checked previews of other styles as well, and it is happening there too.
If I bring up the preview of the building, and _first_ rotate it, _then_ mirror it and scroll through each level only level 1 stays in the place I put it
image
This is level one in preview, rotated, then mirrored 

image
This is as soon as I change to level 2

And to add to weirdness, it does not happen when I am facing North or South, only East and West. 

If I mirror it first, then rotate it, the previews all stay in the right place, just the hut block is backwards.

One time I did it the builder DID actually start building it in the wrong position too - I just can't reliably replicate that

### Expected Behavior

Expect it all to look right

### Reproduction Steps

All the steps are above I think! Face east or West, rotate, then mirror, watch weird things happen!

### Logs

https://gist.github.com/Talyda/70336877926ec7ad35c6f6ed27db44ff

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Thodor12**
Closes #389 
Closes ldtteam/minecolonies#8719

# Changes proposed in this pull request:
- Separates rotation and mirror steps upon selecting a new blueprint, causing the rendered blueprint to retain the same orientation as previously selected schematic

Review please

### CODE REVIEW

**Comment by uecasm** [comment]
Why does this want to do the rotation and mirror in the opposite order from how everything else everywhere does it?  That seems suspicious, since rotate then mirror produces a different result from mirror then rotate.

**Comment by Thodor12** [comment]
> Why does this want to do the rotation and mirror in the opposite order from how everything else everywhere does it? That seems suspicious, since rotate then mirror produces a different result from mirror then rotate.

This only separates the rotation and mirroring, just like you can do if you were to rotate and then mirror by clicking the buttons on the build tool.
The actual rotation and mirror logic is still set in that method, and that hasn't changed (the `rotateWithMirror` method)

The issue is that the method fails if the rotation and mirror are changed simultaneously, I spent some time trying to figure out why but eventually fell back to this as Ray also didn't know this old implementation so well anymore either.

**Comment by Nightenom** [comment]
It looks wierd to call the method twice, please don't merge, will look myself and merge next week

**Comment by uecasm** [comment]
> This only separates the rotation and mirroring, just like you can do if you were to rotate and then mirror by clicking the buttons on the build tool.
The actual rotation and mirror logic is still set in that method, and that hasn't changed (the rotateWithMirror method)

Yeah, but inside that method it does the mirror first and the rotate second.  It also seems weird to only change this one call of it when it's used in a huge number of places.

**Comment by Thodor12** [comment]
The specific use case for this is, when you rotate and mirror a schematic, then proceed to choose another schematic, this method will want to rotate and mirror the schematic at the same time.
This functionality breaks and will actually render the schematic without any rotation/mirror applied to it, whilst the blueprint rendered still thinks it has a rotation/mirror.
This causes the preview and actual schematic to run out of sync, if you then proceed to paste the schematic it will actually revert to the original intended destination.

This is what players were seeing, thinking that the schematic rotation itself was broken.

**Comment by Raycoms** [comment]
> It looks wierd to call the method twice, please don't merge, will look myself and merge next week

@Nightenom done already?

**Pull request closed without merging**
