### PR TITLE
Add nether blocks

### PR DESCRIPTION
**Pull request by ravenbuilder934**
Closes #
Closes #
Closes #

# Changes proposed in this pull request:
- Adds crimson and warped paperwalls, shingles, timberframes
- Adds blackstone timberframes
- Adds blackstone and gilded blackstone shingles
- Fix stone brick timberframes recipes (I did a derp and put `stone_brick` instead of `stone_bricks`)

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit: @Nightenom can we?

**Comment by ShadowProtocol** [comment]
My PR will change this process around slightly. But it's a pretty easy one to switch around so do what you like.

**Comment by Raycoms** [comment]
@ShadowProtocol whatever you prefer, I'm not in a hurry.

**Comment by Nightenom** [comment]
@ShadowProtocol the datagen jsons are now sorted incl. lang file, either update datagen dependency or keep the sorting

**Comment by ShadowProtocol** [comment]
The forge providers all keep them sorted, so we can remove the datagenerators dependency, but that's not what I was referring to for this PR. I  directly alter the timber frame enums in code. The genned files here should theoretically look the same.

**Pull request merged**
