### PR TITLE
no z fighting

### PR DESCRIPTION
**Pull request by someaddons**
Closes #
Closes #
Closes #

# Changes proposed in this pull request:
-
-
-

Review please

### CODE REVIEW

**Review by Nightenom — COMMENTED** [review]
I would make it at least config, also this might not work in higher numbers but w/e

**Comment by someaddons** [comment]
seems to work fine at 500k 500k out still, though interestingly I found a different issue, being so far out causes the preview to wobble with player rotation(even without this change)

**Comment by Raycoms** [comment]
On newest struct?

-------- Original Message --------

**Comment by someaddons** [comment]
ye

**Comment by Nightenom** [comment]
> Member Author

**Comment by Nightenom** [comment]
> seems to work fine at 500k 500k out still, though interestingly I found a different issue, being so far out causes the preview to wobble with player rotation(even without this change)

whoopsie close.. yeah you've reported this issue earlier this year, havent got to it yet

**Comment by someaddons** [comment]
ooh you're right, was when I had a coordinate issue with tavern sitting entities aswell :D

**Pull request merged**
