### PR TITLE
fix #222

### LINKED ISSUE #222: [Bridge fixed][Cannot load&place blueprints] IAngerable entities requires ServerWorld
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.16.3
- MineColonies Version: 13.360 BETA
- Structurize Version:  13.92 ALPHA

## Expected behavior
the build tool GUI opening and letting me place the next building.

## Actual behavior
on clicking "Use Build Tool" the game freezes and then crashes.

## Steps to reproduce the issue

First, I placed down a Tavern Block
Then It suggested me like usually if I want to place it as a block or use the Build Tool
After that I chose the Build Tool option on which the game froze and crashed.

### Logs

- latest.log: https://gist.github.com/SylviaFox/ccb342067241f7bda1dbcf90145560ab
- crashlog:  https://gist.github.com/SylviaFox/52e464f722feb6544ca737066a9104b5

### Notes
I just played normally, this happend to me, on my Survival World where I had several buildings already ,with the Shepherd's Hut. I then proceeded to open a Creative world to see if it was just the one building. It worked fine at first, built my Builder's Hut, a Mine and sent my builder to now build a farm. Wanted to plan ahead but was stopped lol.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Raycoms**
Progress towards #222 and #202

# Changes proposed in this pull request:
- Fixes wolf crash
-
-

Review please

Edit Nightenom: don't close the issue

### CODE REVIEW

**Review by marchermans — CHANGES_REQUESTED** [review]
Since this now seems to keep on happening with different types, I suggest this gets moved into the ServerConfiguration, that checks for the registry name of the entity type.

**Review by Nightenom — CHANGES_REQUESTED** [review]
I have exactly told you what to do, this is not IAngerable check :D
To Orion: nah, I don't want to have a config for this, and it would be Client config btw

**Comment by Raycoms** [comment]
@Nightenom I looked into it, and I don't want to hold up loading.
Atm at that place you mentioned we don't load any entities. the most I could do is add a "string" match for the compound data.

**Comment by Raycoms** [comment]
Besides, that's the place where we had the iron golem fix already.

**Comment by Nightenom** [comment]
Yep, I see, but this is not `instanceof IAngerable` check :D

**Comment by Raycoms** [comment]
Yeah, I wanted to put it in line with the Iron golem thing. I'll do the config setting though, I think that's a good idea that will keep us from this issue in the future

**Comment by Nightenom** [comment]
config thing is the same type of solution as request system reset command, I want to be aware of all entities causing this, for now, it's all IAngerable since that's where the problematic method is, afaik Iron Golem is IAngerable too

**Comment by Raycoms** [comment]
@Nightenom oh the config is not for players to add to. it's more so that we can quite easily add stuff to it.

**Comment by Raycoms** [comment]
Meh, make a PR afterwards if not happy

**Pull request merged**
