### PR TITLE
Update Gradle Wrapper for 1.14

### PR DESCRIPTION
**Pull request by Asherslab**
Title

### CODE REVIEW

**Review by marchermans — COMMENTED** [review]
Revert this. Max gradle version for fg3 is 4.9

**Comment by Asherslab** [comment]
I literally can’t use it on 4.9, only on this 5.5.1 version. Kept getting crashes till I updated

**Comment by Asherslab** [comment]
got it working. had to fully reinstall gradle

**Comment by marchermans** [comment]
Not supported. Ask lex it is specified in the fg3 source.

**Comment by Asherslab** [comment]
nono, i meant that i got 4.9 working. had to reinstall it. it kept crashing any time i'd run FG3 on it

**Comment by marchermans** [comment]
4.9 Is the max version for Gradle when running under FG3.
Anything higher will make it fail to resolve certain dependencies.

**Pull request merged**
