### PR TITLE
Model Optimizations

### LINKED ISSUE #4139: Inconsistent Item Display Properties
### Minecraft & Forge version
`Version: 1.14.4-28.1.104`

### Minecolonies version
`Version: 0.10.588-BETA`

### Structurize version
`Version: 0.10.201-ALPHA`

### Expected behavior

-  Items should have display properties similar to normal Minecraft blocks, such as stone, dirt, or grass for the inventory, Item Frames, the main/off-hand, & in First/Third-Person View.

### Actual behaviour

-  Instead, items have inconsistent sizes.
- For example, some hut blocks are quite small, while others are bigger than the inventory slot.
- Another example is the compost dirt block & the Multi-piston. They are too large in both the inventory and when held in the hand. 
  - (Compost Dirt also is missing the dirt sound when placed & is using the old farmland texture.) 
  - (Multi-Pistons are missing the breaking texture.)
- Timber Frames display pretty small despite being the same size as a normal block.
- The Compost Bin, the Archery Hut Block, and the Decoration Controller are rotated oddly.
  - Otherwise, just a minor issue.

A few examples:

### Steps to reproduce the problem

1. View Minecolonies and Structurize blocks in the creative tabs.
2. Compare to other Minecraft blocks.
4. ... Profit

### PR DESCRIPTION
**Pull request by WenXin20**
Closes ldtteam/minecolonies#4139

# Changes proposed in this pull request:
- Optimizes Multiblock model
- Fixes item display properties
- Updates the placeholder & substitution blocks to the 1.14+ texture for planks

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
Is this ready to be merged?

**Comment by WenXin20** [comment]
Yeah, should be

**Comment by Asherslab** [comment]
this was ***not*** ready to merge
you can't just directly edit files under a generated directory
@WenXin20 
Those files are data generated

**Comment by WenXin20** [comment]
I hadn't realized they were data generated. I was mainly trying to fix the item display properties, such as with item frames.

Does #117 fix it already?

**Comment by Asherslab** [comment]
@WenXin20 Correct.
In the future please make sure to read why a directory might be named `generated`

**Pull request merged**
