### PR TITLE
Fix fog setup inside level render events

### PR DESCRIPTION
**Pull request by Nightenom**
# Changes proposed in this pull request:
- fix changes in fog setup when inside non-AFTER_LEVEL renderWorldEvents

Review please

### CODE REVIEW

**Review by Raycoms — APPROVED** [review]

**Review by marchermans — APPROVED** [review]

**Review by uecasm — APPROVED** [review]
This does seem to fix it.  Although that begs the question of whether it's intended that it redraws everything at all the render stages.  Isn't it more typical to only draw at one stage?  Or to draw specific things at specific stages?

**Comment by uecasm** [comment]
Hmm.  Actually, it does only get called at one stage, so this code change has the effect of never calling that fog code at all, as far as I can tell.

In Structurlze, `ClientEventSubscriber` calls `draw` only at one of `Stage.AFTER_CUTOUT_MIPPED_BLOCKS_BLOCKS` or `Stage.AFTER_TRANSLUCENT_BLOCKS` depending on the translucency setting.

In MineColonies, `WorldEventContext` calls `draw` only at `Stage.AFTER_CUTOUT_MIPPED_BLOCKS_BLOCKS`.  (Possibly it needs to similarly check the setting?)

So there is no case when the `if` blocks would be entered. which suggests either that the code could just be deleted entirely, or this isn't the intended fix.

**Review by uecasm — CHANGES_REQUESTED** [review]
Per above, this doesn't seem quite right after all.

**Comment by Nightenom** [comment]
Yeah, I know code I made :D end-users may currently render blueprints possibly at any stage (this renderer replicates entire LevelRenderer#renderLevel(...) method up to the most reproducible point, so it doesnt really care from which context it has been called)

**Pull request merged**
